---
abstract: 'An asynchronous and multi channel Perl AMQP client.'
author:
  - 'Masahito Ikuta <cooldaemon@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::More: 0
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-RabbitMQ
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  AnyEvent: 0
  Devel::GlobalDestruction: 0
  File::ShareDir: 0
  List::MoreUtils: 0
  Net::AMQP: 0
  Readonly: 1.03
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/AnyEvent-RabbitMQ.git
version: 1.0701
